apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: quantis-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-staging
spec:
  tls:
    - hosts:
        - dev.quantis.example.com
      secretName: quantis-tls
  rules:
    - host: dev.quantis.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: quantis-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: quantis-frontend
                port:
                  number: 80
